local DiscordLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/dawid-scripts/UI-Libs/main/discord%20lib.txt"))()
local win = DiscordLib:Window("nhà tài chợ Discord library")
local serv = win:Server("HRhack :)", "")

-- Tạo danh sách các tên bản script
local FS = serv:Channel("Forsaken")
local SB = serv:Channel("???")
local DR = serv:Channel("???")
local SAB = serv:Channel("???")
local R = serv:Channel("???")
local SH = serv:Channel("???")
local C = serv:Channel("???")
local A = serv:Channel("Other Script")

-- Tạo danh sách bản script
FS:Button("Hutao Hub", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/hdksakst-ship-it/Hutao-Hub-Omega-X/refs/heads/main/Forsaken-V4-Fix.txt"))()
end)
FS:Button("SNT Hub", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Snowt69/SNT-HUB/refs/heads/main/Forsaken"))()
end)
FS:Button("NOL", function()
getfenv().ADittoKey="NOL_FRERKEY"---Put in key
loadstring(game:HttpGet("https://raw.githubusercontent.com/Syndromehsh/NOL/refs/heads/main/Nolsaken"))()
end)
FS:Button("Veronica Auto Trick", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/scriptluckisreal/AutoTheTrick/refs/heads/main/Autothetrickscript"))()
end)
A:Button("Infinite Yield", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
A:Button("Mobile KeyBoard", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()
end)
A:Button("Fly Gui V3", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Fly%20Gui%20V3"))()
end)
A:Button("Ghost Hub", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/GhostPlayer352/Test4/main/GhostHub'))()
end)
A:Button("HitBox", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/HitBox"))()
end)
A:Button("Simple Spy Mobile", function()
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Simple-Spy-Mobile-Script-Restored-22732"))()
end)
A:Button("Vfly", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/GhostPlayer352/Test4/main/Vehicle%20Fly%20Gui'))()
end)
A:Button("Omg Hub", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Omgshit/Scripts/main/MainLoader.lua"))()
end)
A:Button("Free Gamepass", function()
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-UNIVERSAL-FREE-GAMEPASS-OR-DEV-PRODUCT-PURCHASER-SCRIPT-41286"))()
end)
A:Button("Drop Gui", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Drop%20Gui"))()
end)
A:Button("Fling Gui", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/0Ben1/fe./main/Fling%20GUI"))()
end)
A:Button("Orange X V5", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ImJosh66/Ab2rW/main/ORANGEX%20V5%20RELEASED%20ORANGEX%20ON%20TOP%20.txt"))()
end)
A:Button("Fe Freeze", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/SavaLava9/FEFreeze/main/FEFreeze.txt"))()
end)
A:Button("Rochips Universal", function()
loadstring(game:HttpGet("https://rawscripts.net/raw/Brookhaven-RP-Rochips-Universal-21865"))()
end)
A:Button("Tool Vip", function()
loadstring(game:HttpGet(('https://pastefy.app/VYIAk3o1/raw'),true))()
end)
A:Button("Climb", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/0Ben1/fe/main/obf_vZDX8j5ggfAf58QhdJ59BVEmF6nmZgq4Mcjt2l8wn16CiStIW2P6EkNc605qv9K4.lua.txt'))()
end)
A:Button("illusion", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/0Ben1/fe/main/obf_11l7Y131YqJjZ31QmV5L8pI23V02b3191sEg26E75472Wl78Vi8870jRv5txZyL1.lua.txt"))()
end)
A:Button("God Mode", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/zephyr10101/ignore-touchinterests/main/main",true))()
end)
A:Button("Kill NPC", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Kill%20NPC"))()
end)
A:Button("Copy Id Animation", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Mautiku/ehh/main/sussy's%20animation%20logger.txt",true))()
end)
A:Button("Fe Xu Card Lép R6", function()
loadstring(game:HttpGet("https://pastefy.app/wa3v2Vgm/raw"))()
end)
A:Button("Fe Xu Card Lép R15", function()
loadstring(game:HttpGet("https://pastefy.app/YZoglOyJ/raw"))()
end)
A:Button("Fe Dash R6/R15", function()
loadstring(game:HttpGet("https://pastefy.app/ZhKVgCK3/raw"))()
end)
A:Button("Fe Fighter R6", function()
loadstring(game:HttpGet("https://pastefy.app/wxVAgZpT/raw"))()
end)
A:Button("Fe Zomblie R6", function()
loadstring(game:HttpGet("https://pastefy.app/JOWniO6o/raw"))()
end)
A:Button("Fe SCP 096 R6", function()
loadstring(game:HttpGet("https://pastefy.app/YsJgITXR/raw"))()
end)
A:Button("Fe Seraphic Blade R6", function()
loadstring(game:HttpGet("https://pastefy.app/59mJGQGe/raw"))()
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Touch-fling-10457"))()
end)
A:Button("Position Finder", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/GamerScripter/Position-Finder/main/loader"))()
end)
A:Button("Anti AFK", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/KazeOnTop/Rice-Anti-Afk/main/Wind", true))()
end)
A:Button("Auto Click Mighty", function()
getgenv().key = "Hostile"
loadstring(game:HttpGet("https://raw.githubusercontent.com/Hosvile/The-telligence/main/MC%20KSystem%202"))()
end)
A:Button("c00lgui", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/MiRw3b/c00lgui-v3rx/main/c00lguiv3rx.lua"))()
end)
A:Button("invisible", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Fe%20invisible"))()
end)
