local DiscordLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/dawid-scripts/UI-Libs/main/discord%20lib.txt"))()
local win = DiscordLib:Window("nhà tài chợ Discord library")
local serv = win:Server("HRhack :)", "")

-- Tạo danh sách các tên bản script
local W = serv:Channel("The Strongest Battleground")
local M = serv:Channel("Fisch")
local ST = serv:Channel("A Dusty Trip")
local OP = serv:Channel("jujutsu shenanigans")
local S = serv:Channel("The Mimic")
local B = serv:Channel("Blox Fruit")
local SB = serv:Channel("Slap Battles")
local BL = serv:Channel("Blue Lock Rival")
local DR = serv:Channel("Dead Rails")
local SV = serv:Channel("???")
local D = serv:Channel("???")
local R = serv:Channel("???")
local SH = serv:Channel("???")
local C = serv:Channel("???")
local A = serv:Channel("Other Script")

-- Tạo danh sách bản script
W:Button("FFJ1", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/FFJ1/Roblox-Exploits/main/scripts/TSBUtils.lua"))()
end)
W:Button("Run And Flash Step", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/The-Strongest-Battlegrounds/refs/heads/main/Run%20And%20Flash%20Step"))()
end)
W:Button("Fake DownSlam", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Mautiku/ehh/refs/heads/main/Fake%20downslam.txt"))()
end)
W:Button("Gojo 1/2 To Saitama", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/skibiditoiletfan2007/BaldyToSorcerer/refs/heads/main/LatestV2.lua"))()
end)
W:Button("Jun To Saitama", function()
getgenv().sendChat = false
getgenv().BetterGraphics = false
loadstring(game:HttpGet"https://raw.githubusercontent.com/wispwisp22/Limitless-legacy/refs/heads/main/ReuploadedJun")()
end)
W:Button("Bắn Tùm Lum ĐẾN Garou :)", function()
loadstring(game:HttpGet("https://paste.ee/r/gKC8V"))()
end)
W:Button("Deku to Garou", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/The-Strongest-Battlegrounds/refs/heads/main/Mastery%20Deku"))()
end)
W:Button("Hakari To Saitama", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/The-Strongest-Battlegrounds/refs/heads/main/Hakari"))()
end)
W:Button("Toji To Samurai", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Giahao135/Tojifushiguro/refs/heads/main/Togiiiii"))()
end)
W:Button("Minos Prime V1 To Garou", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/The-Strongest-Battlegrounds/refs/heads/main/Minos%20Prime%20V1"))()
end)
W:Button("Minos Prime V2 To Garou", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/S1gmaGuy/Minosprime/refs/heads/main/Minos%20prime%20finally%20released"))()
end)
W:Button("Titan To All Characters", function()
loadstring(game:HttpGet("https://paste.ee/r/fxY03"))()
end)
W:Button("kizaru To Garou", function()
loadstring(game:HttpGet("https://paste.ee/r/NPnfk"))()
end)
W:Button("KJ To Garou", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/damir512/garoukjv1maybeidk/main/Protected_2460290213750059.txt",true))()
end)
W:Button("Mahito To Suiryu", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/GreatestLime4K/mahitotsb/refs/heads/main/Protected_6381580361331378.txt'))()
end)
W:Button("Vexor To Saitama", function()
loadstring(game:HttpGet("https://paste.ee/r/PDaAI"))()
end)
W:Button("KJ To Saitama", function()
loadstring(game:HttpGet("https://gist.githubusercontent.com/GoldenHeads2/5fe3178dff916f988d319c3bd5e4fc01/raw/b250ee6f967c4e84195a76ab7915fb1d79b53326/gistfile1.txt"))()
end)
W:Button("Chainsaw Man To Ninja", function()
loadstring(game:HttpGet("https://gist.githubusercontent.com/GoldenHeads2/0fd8d36993c850f3fac89e5adf793076/raw/ab4f5a42bd0b2e24a32a46301d533ea849ca771c/gistfile1.txt"))()
end)
W:Button("Shinji To Saitama", function()
getgenv().speedtools = true --- use this tool if you want to run
getgenv().speedpunch= true ---tp and normal Punch (have a bug)
getgenv().dance= true ---song made by rebzyyx all I want is you 
getgenv().night= false -- idk night?
loadstring(game:HttpGet('https://raw.githubusercontent.com/Kenjihin69/Kenjihin69/refs/heads/main/Shinji%20tp%20exploit'))()
end)
W:Button("Luffy To Saitama", function()
loadstring(game:HttpGet("https://github.com/aggiealledge/obfuscated-scripts/raw/refs/heads/main/Protected_7732857839120517.txt"))()
end)
W:Button("Deku To Suiryu", function()
loadstring(game:HttpGet("https://github.com/aggiealledge/obfuscated-scripts/raw/refs/heads/main/deku%20suiryu%20thingy.txt"))()
end)
W:Button("Trash Can Man To All Characters", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/yes1nt/yes/refs/heads/main/Trashcan%20Man", true))()
end)
W:Button("JK To KJ", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/NetlessMade/KJ-TO-JK/refs/heads/main/script.lua"))()
end)
W:Button("Sung Jin Woo To Saitama", function()
loadstring(game:HttpGet("https://gist.githubusercontent.com/GoldenHeads2/bf280c4c46317fc8bec986921113e057/raw/63436c35a945633bec4a7e6484d86a0a2c77fac6/gistfile1.txt"))()
end)
W:Button("Choi Jong in To Saitama", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/nil071n/fireman/refs/heads/main/TSB"))()
end)
W:Button("1x1x1x1 To Ninja", function()
loadstring(game:HttpGet("https://gist.githubusercontent.com/GoldenHeads2/900e87ffc32f3c740930ccb106dd6abf/raw/358c5bf0f0a6aa25946718288dab006e3ae7e1d4/gistfile1.txt"))()
end)
W:Button("Star Glitchers To 4 Characters", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Reapvitalized/TSB/refs/heads/main/SG_DEMO.lua"))()
end)
W:Button("Void Garou To Garou", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/yes1nt/yes/refs/heads/main/Void%20Reaper%20Obfuscated.txt"))()
end)
W:Button("A Train To Garou", function()
getgenv().settings = {
["morph"] = {
["enabled"] = false,
["dontchangeskincolor"] = false,},
["ult_forcewalkspeed"] = true, -- forces walkspeed even if set to 0
["ult_walkspeed"] = 64, -- how fast you walk in ult
["tp_duration"] = 0.15 -- how long it takes to tp
} 
loadstring(game:HttpGet("https://raw.githubusercontent.com/skibiditoiletfan2007/ATrainSounds/refs/heads/main/ATrain.lua"))()
end)
M:Button("Speed Hub X", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/AhmadV99/Speed-Hub-X/main/Speed%20Hub%20X.lua", true))()
end)
ST:Button("Nurk Hub Dupe V2", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/AbdouGG/Nurk-Hub/main/DuperV2"))()
end)
OP:Button("Auto Black Flash", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/jujutsu-shenanigans/refs/heads/main/Auto%20Black%20Flash"))()
end)
OP:Button("Xenon Hub V2", function()
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/7fe29a6a9dc2a08c84b8e2f0f5ef5810.lua"))()
end)
B:Button("HoHo Hub", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/acsu123/HOHO_H/main/Loading_UI"))()
end)
B:Button("Van Thanh Hitbox", function()
loadstring(Game:HttpGet("https://raw.githubusercontent.com/VanThanhIOS/OniiChanVanThanhIOS/refs/heads/main/oniichanpakavanthanhios"))()
end)
SB:Button("Giang Play", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/giangplay/Slap_Battles/main/Slap_Battles.lua"))()
end)
SB:Button("All Glove Mastery", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/DonjoScripts/Public-Scripts/refs/heads/Slap-Battles/MasteryHelperV1.lua'))()
end)
SB:Button("Free Get Badge", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/IncognitoScripts/SlapBattles/refs/heads/main/BadgesHub"))();
end)
SB:Button("Pillow Panel", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Rakeroblox123/PillowPanel/refs/heads/main/Protected_3962207669401083.txt"))()
end)
SB:Button("Auto Farm Bob", function()
loadstring(game:HttpGet(('https://raw.githubusercontent.com/Donjosx/SBScriptsLink/refs/heads/main/BobFarm%5Bunpatched%5D'),true))()
end)
SB:Button("Auto Rob", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Dusty1234567890/Rob/main/Rob"))()
end)
BL:Button("Arbix Hub Auto Gk", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Youifpg/Arbix--Hub/refs/heads/main/Blue!ock.lua"))()
end)
BL:Button("Auto Dribble", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Blue-Lock-Rival/refs/heads/main/Auto%20Dribble"))()
end)
BL:Button("Magnet Ball", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Blue-Lock-Rival/refs/heads/main/Magnet%20Ball"))()
end)
BL:Button("Pillar Chase", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Bhusant/Pillar-chase/refs/heads/main/KeySystem"))()
end)
BL:Button("Control Ball", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/RedJDark/CONTROL-SCRIPTT/refs/heads/main/CONTROL"))()
end)
BL:Button("No Cooldown Ability", function()
local C=require(game:GetService("ReplicatedStorage").Controllers.AbilityController)
local o=C.AbilityCooldown C.AbilityCooldown=function(s,n,...)return o(s,n,0,...)end
end)
BL:Button("Juke", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/RedJDark/MAIN/refs/heads/main/juke"))()
end)
BL:Button("Reo Copy Style And Flow", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Blue-Lock-Rival/refs/heads/main/Reo%20Copy%20Style%20And%20Flow"))()
end)
DR:Button("Supra Hub", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Super-XXX-Source/DEAD-RAILS-/refs/heads/main/DEAD%20RAILS%20SUPRA%20HUB"))()
end)
DR:Button("Null Fire", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/InfernusScripts/Null-Fire/main/Loader"))()
end)
DR:Button("Auto Win", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/gumanba/Scripts/main/DeadRails"))()
end)
A:Button("Infinite Yield", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
A:Button("Mobile KeyBoard", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()
end)
A:Button("Fly Gui V3", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Fly%20Gui%20V3"))()
end)
A:Button("Ghost Hub", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/GhostPlayer352/Test4/main/GhostHub'))()
end)
A:Button("HitBox", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/HitBox"))()
end)
A:Button("Simple Spy Mobile", function()
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Simple-Spy-Mobile-Script-Restored-22732"))()
end)
A:Button("Vfly", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Vfly"))()
end)
A:Button("Omg Hub", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Omgshit/Scripts/main/MainLoader.lua"))()
end)
A:Button("Drop Gui", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Drop%20Gui"))()
end)
A:Button("Fling Gui", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/0Ben1/fe./main/Fling%20GUI"))()
end)
A:Button("Orange X V5", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ImJosh66/Ab2rW/main/ORANGEX%20V5%20RELEASED%20ORANGEX%20ON%20TOP%20.txt"))()
end)
A:Button("Fe Freeze", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/SavaLava9/FEFreeze/main/FEFreeze.txt"))()
end)
A:Button("Rochips Universal", function()
loadstring(game:HttpGet("https://rawscripts.net/raw/Brookhaven-RP-Rochips-Universal-21865"))()
end)
A:Button("Tool Vip", function()
loadstring(game:HttpGet(('https://pastefy.app/VYIAk3o1/raw'),true))()
end)
A:Button("Climb", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/0Ben1/fe/main/obf_vZDX8j5ggfAf58QhdJ59BVEmF6nmZgq4Mcjt2l8wn16CiStIW2P6EkNc605qv9K4.lua.txt'))()
end)
A:Button("illusion", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/0Ben1/fe/main/obf_11l7Y131YqJjZ31QmV5L8pI23V02b3191sEg26E75472Wl78Vi8870jRv5txZyL1.lua.txt"))()
end)
A:Button("God Mode", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/zephyr10101/ignore-touchinterests/main/main",true))()
end)
A:Button("Kill NPC", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Kill%20NPC"))()
end)
A:Button("Copy Id Animation", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Mautiku/ehh/main/sussy's%20animation%20logger.txt",true))()
end)
A:Button("Fe Xu Card Lép R6", function()
loadstring(game:HttpGet("https://pastefy.app/wa3v2Vgm/raw"))()
end)
A:Button("Fe Xu Card Lép R15", function()
loadstring(game:HttpGet("https://pastefy.app/YZoglOyJ/raw"))()
end)
A:Button("Fe Dash R6/R15", function()
loadstring(game:HttpGet("https://pastefy.app/ZhKVgCK3/raw"))()
end)
A:Button("Fe Fighter R6", function()
loadstring(game:HttpGet("https://pastefy.app/wxVAgZpT/raw"))()
end)
A:Button("Fe Zomblie R6", function()
loadstring(game:HttpGet("https://pastefy.app/JOWniO6o/raw"))()
end)
A:Button("Fe SCP 096 R6", function()
loadstring(game:HttpGet("https://pastefy.app/YsJgITXR/raw"))()
end)
A:Button("Fe Seraphic Blade R6", function()
loadstring(game:HttpGet("https://pastefy.app/59mJGQGe/raw"))()
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Touch-fling-10457"))()
end)
A:Button("Position Finder", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/GamerScripter/Position-Finder/main/loader"))()
end)
A:Button("Anti AFK", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/KazeOnTop/Rice-Anti-Afk/main/Wind", true))()
end)
A:Button("Auto Click Mighty", function()
getgenv().key = "Hostile"
loadstring(game:HttpGet("https://raw.githubusercontent.com/Hosvile/The-telligence/main/MC%20KSystem%202"))()
end)
A:Button("invisible", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Fe%20invisible"))()
end)
