local DiscordLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/dawid-scripts/UI-Libs/main/discord%20lib.txt"))()
local win = DiscordLib:Window("nhà tài chợ Discord library")
local serv = win:Server("HRhack :)", "")

-- Tạo danh sách các tên bản script
local FS = serv:Channel("Forsaken")
local SB = serv:Channel("Slap Battles")
local DR = serv:Channel("Dead Rails")
local SAB = serv:Channel("Steal A Brainrot")
local R = serv:Channel("???")
local SH = serv:Channel("???")
local C = serv:Channel("???")
local A = serv:Channel("Other Script")

-- Tạo danh sách bản script
FS:Button("Rift", function()
loadstring(game:HttpGet("https://rifton.top/loader.lua"))()
end)
FS:Button("Goa Hub", function()
_G.Key = "goaHuB41"
loadstring(game:HttpGet("https://raw.githubusercontent.com/Nevcit/GOA_HUB/refs/heads/main/Forsaken", true))()
end)
SB:Button("Giang Play", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/giangplay/Slap_Battles/main/Slap_Battles.lua"))()
end)
SB:Button("All Glove Mastery", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/DonjoScripts/Public-Scripts/refs/heads/Slap-Battles/MasteryHelperV1.lua'))()
end)
SB:Button("Free Get Badge", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/IncognitoScripts/SlapBattles/refs/heads/main/BadgesHub"))();
end)
SB:Button("Pillow Panel", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Rakeroblox123/PillowPanel/refs/heads/main/Protected_3962207669401083.txt"))()
end)
SB:Button("Auto Farm Bob", function()
loadstring(game:HttpGet(('https://raw.githubusercontent.com/Donjosx/SBScriptsLink/refs/heads/main/BobFarm%5Bunpatched%5D'),true))()
end)
SB:Button("Auto Rob", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Dusty1234567890/Rob/main/Rob"))()
end)
SB:Button("God Mode", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/IncognitoScripts/SlapBattles/refs/heads/main/GodMode"))()
end)
DR:Button("Null Fire", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/InfernusScripts/Null-Fire/main/Loader"))()
end)
SAB:Button("Makai Hub", function()
local a,b,c=loadstring,(syn and syn.request)or(http and http.request)or(request)or(http_request),assert;c(a and b,"Executor not Supported")a(b({Url="https://makalhub.vercel.app/api/script/loader",Method="GET"}).Body)()
end)
A:Button("Infinite Yield", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
A:Button("Mobile KeyBoard", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()
end)
A:Button("Fly Gui V3", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Fly%20Gui%20V3"))()
end)
A:Button("Ghost Hub", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/GhostPlayer352/Test4/main/GhostHub'))()
end)
A:Button("HitBox", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/HitBox"))()
end)
A:Button("Simple Spy Mobile", function()
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Simple-Spy-Mobile-Script-Restored-22732"))()
end)
A:Button("Vfly", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/GhostPlayer352/Test4/main/Vehicle%20Fly%20Gui'))()
end)
A:Button("Omg Hub", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Omgshit/Scripts/main/MainLoader.lua"))()
end)
A:Button("Free Gamepass", function()
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-UNIVERSAL-FREE-GAMEPASS-OR-DEV-PRODUCT-PURCHASER-SCRIPT-41286"))()
end)
A:Button("Drop Gui", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Drop%20Gui"))()
end)
A:Button("Fling Gui", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/0Ben1/fe./main/Fling%20GUI"))()
end)
A:Button("Orange X V5", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ImJosh66/Ab2rW/main/ORANGEX%20V5%20RELEASED%20ORANGEX%20ON%20TOP%20.txt"))()
end)
A:Button("Fe Freeze", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/SavaLava9/FEFreeze/main/FEFreeze.txt"))()
end)
A:Button("Rochips Universal", function()
loadstring(game:HttpGet("https://rawscripts.net/raw/Brookhaven-RP-Rochips-Universal-21865"))()
end)
A:Button("Tool Vip", function()
loadstring(game:HttpGet(('https://pastefy.app/VYIAk3o1/raw'),true))()
end)
A:Button("Climb", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/0Ben1/fe/main/obf_vZDX8j5ggfAf58QhdJ59BVEmF6nmZgq4Mcjt2l8wn16CiStIW2P6EkNc605qv9K4.lua.txt'))()
end)
A:Button("illusion", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/0Ben1/fe/main/obf_11l7Y131YqJjZ31QmV5L8pI23V02b3191sEg26E75472Wl78Vi8870jRv5txZyL1.lua.txt"))()
end)
A:Button("God Mode", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/zephyr10101/ignore-touchinterests/main/main",true))()
end)
A:Button("Kill NPC", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Kill%20NPC"))()
end)
A:Button("Copy Id Animation", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Mautiku/ehh/main/sussy's%20animation%20logger.txt",true))()
end)
A:Button("Fe Xu Card Lép R6", function()
loadstring(game:HttpGet("https://pastefy.app/wa3v2Vgm/raw"))()
end)
A:Button("Fe Xu Card Lép R15", function()
loadstring(game:HttpGet("https://pastefy.app/YZoglOyJ/raw"))()
end)
A:Button("Fe Dash R6/R15", function()
loadstring(game:HttpGet("https://pastefy.app/ZhKVgCK3/raw"))()
end)
A:Button("Fe Fighter R6", function()
loadstring(game:HttpGet("https://pastefy.app/wxVAgZpT/raw"))()
end)
A:Button("Fe Zomblie R6", function()
loadstring(game:HttpGet("https://pastefy.app/JOWniO6o/raw"))()
end)
A:Button("Fe SCP 096 R6", function()
loadstring(game:HttpGet("https://pastefy.app/YsJgITXR/raw"))()
end)
A:Button("Fe Seraphic Blade R6", function()
loadstring(game:HttpGet("https://pastefy.app/59mJGQGe/raw"))()
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Touch-fling-10457"))()
end)
A:Button("Position Finder", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/GamerScripter/Position-Finder/main/loader"))()
end)
A:Button("Anti AFK", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/KazeOnTop/Rice-Anti-Afk/main/Wind", true))()
end)
A:Button("Auto Click Mighty", function()
getgenv().key = "Hostile"
loadstring(game:HttpGet("https://raw.githubusercontent.com/Hosvile/The-telligence/main/MC%20KSystem%202"))()
end)
A:Button("c00lgui", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/MiRw3b/c00lgui-v3rx/main/c00lguiv3rx.lua"))()
end)
A:Button("invisible", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/HRhack55/Script/refs/heads/main/Fe%20invisible"))()
end)
